// Code generated by gen --type=GameProfileProperty; DO NOT EDIT.

package packets

import (
	"io"
)

func DeserializeGameProfileProperty(reader io.Reader) (GameProfileProperty, int, error) {

	fieldName, _, err := DeserializeString(reader)
	if err != nil {
		return GameProfileProperty{}, 0, err
	}

	fieldValue, _, err := DeserializeString(reader)
	if err != nil {
		return GameProfileProperty{}, 0, err
	}

	fieldSignature, _, err := DeserializeBoolean(reader)
	if err != nil {
		return GameProfileProperty{}, 0, err
	}

	return GameProfileProperty{
		Name: fieldName,

		Value: fieldValue,

		Signature: fieldSignature,
	}, 0, nil
}

func (p GameProfileProperty) Serialize() ([]byte, error) {
	buffer := make([]byte, 0)

	dataBuffer := make([]byte, 0)

	fieldName, err := p.Name.Serialize()
	if err != nil {
		return nil, err
	}
	dataBuffer = append(dataBuffer, fieldName...)

	fieldValue, err := p.Value.Serialize()
	if err != nil {
		return nil, err
	}
	dataBuffer = append(dataBuffer, fieldValue...)

	fieldSignature, err := p.Signature.Serialize()
	if err != nil {
		return nil, err
	}
	dataBuffer = append(dataBuffer, fieldSignature...)

	buffer = append(buffer, dataBuffer...)

	return buffer, nil
}
