// Code generated by gen --type=GameProfile; DO NOT EDIT.

package packets

import (
	"io"
)

func DeserializeGameProfile(reader io.Reader) (GameProfile, int, error) {

	// {Name:UUID Type:UUID IsJson:false IsPrefixed:false IsArray:false IsOptional:false}

	fieldUUID, _, err := DeserializeUUID(reader)
	if err != nil {
		return GameProfile{}, 0, err
	}

	// {Name:Username Type:String IsJson:false IsPrefixed:false IsArray:false IsOptional:false}

	fieldUsername, _, err := DeserializeString(reader)
	if err != nil {
		return GameProfile{}, 0, err
	}

	// {Name:Properties Type:GameProfileProperty IsJson:false IsPrefixed:true IsArray:true IsOptional:false}

	size, _, err := DeserializeVarInt(reader)
	if err != nil {
		return GameProfile{}, 0, err
	}

	fieldProperties := make([]GameProfileProperty, size)

	for range size {
		nextValue, _, err := DeserializeGameProfileProperty(reader)
		if err != nil {
			return GameProfile{}, 0, err
		}

		fieldProperties = append(fieldProperties, nextValue)
	}

	return GameProfile{
		UUID: fieldUUID,

		Username: fieldUsername,

		Properties: fieldProperties,
	}, 0, nil
}

func (p GameProfile) Serialize() ([]byte, error) {
	buffer := make([]byte, 0)

	dataBuffer := make([]byte, 0)

	// {Name:UUID Type:UUID IsJson:false IsPrefixed:false IsArray:false IsOptional:false}

	fieldUUID, err := p.UUID.Serialize()
	if err != nil {
		return nil, err
	}
	dataBuffer = append(dataBuffer, fieldUUID...)

	// {Name:Username Type:String IsJson:false IsPrefixed:false IsArray:false IsOptional:false}

	fieldUsername, err := p.Username.Serialize()
	if err != nil {
		return nil, err
	}
	dataBuffer = append(dataBuffer, fieldUsername...)

	// {Name:Properties Type:GameProfileProperty IsJson:false IsPrefixed:true IsArray:true IsOptional:false}

	size, err := VarInt(len(p.Properties)).Serialize()
	if err != nil {
		return nil, err
	}
	dataBuffer = append(dataBuffer, size...)

	for _, e := range p.Properties {
		serializedElement, err := e.Serialize()
		if err != nil {
			return nil, err
		}
		dataBuffer = append(dataBuffer, serializedElement...)
	}

	buffer = append(buffer, dataBuffer...)

	return buffer, nil
}
