// Code generated by gen --type=Intention --id=0x01; DO NOT EDIT.

package packets

import (
	"io"
)

func DeserializeIntention(reader io.Reader) (Intention, int, error) {

	// {Name:ProtocolVersion Type:VarInt IsJson:false IsPrefixed:false IsArray:false IsOptional:false}

	fieldProtocolVersion, _, err := DeserializeVarInt(reader)
	if err != nil {
		return Intention{}, 0, err
	}

	// {Name:ServerAddress Type:String IsJson:false IsPrefixed:false IsArray:false IsOptional:false}

	fieldServerAddress, _, err := DeserializeString(reader)
	if err != nil {
		return Intention{}, 0, err
	}

	// {Name:ServerPort Type:UnsignedShort IsJson:false IsPrefixed:false IsArray:false IsOptional:false}

	fieldServerPort, _, err := DeserializeUnsignedShort(reader)
	if err != nil {
		return Intention{}, 0, err
	}

	// {Name:Intent Type:VarInt IsJson:false IsPrefixed:false IsArray:false IsOptional:false}

	fieldIntent, _, err := DeserializeVarInt(reader)
	if err != nil {
		return Intention{}, 0, err
	}

	return Intention{
		ProtocolVersion: fieldProtocolVersion,

		ServerAddress: fieldServerAddress,

		ServerPort: fieldServerPort,

		Intent: fieldIntent,
	}, 0, nil
}

func (p Intention) Serialize() ([]byte, error) {
	buffer := make([]byte, 0)

	packetIdBytes, err := VarInt(1).Serialize()
	if err != nil {
		return nil, err
	}

	dataBuffer := make([]byte, 0)

	// {Name:ProtocolVersion Type:VarInt IsJson:false IsPrefixed:false IsArray:false IsOptional:false}

	fieldProtocolVersion, err := p.ProtocolVersion.Serialize()
	if err != nil {
		return nil, err
	}
	dataBuffer = append(dataBuffer, fieldProtocolVersion...)

	// {Name:ServerAddress Type:String IsJson:false IsPrefixed:false IsArray:false IsOptional:false}

	fieldServerAddress, err := p.ServerAddress.Serialize()
	if err != nil {
		return nil, err
	}
	dataBuffer = append(dataBuffer, fieldServerAddress...)

	// {Name:ServerPort Type:UnsignedShort IsJson:false IsPrefixed:false IsArray:false IsOptional:false}

	fieldServerPort, err := p.ServerPort.Serialize()
	if err != nil {
		return nil, err
	}
	dataBuffer = append(dataBuffer, fieldServerPort...)

	// {Name:Intent Type:VarInt IsJson:false IsPrefixed:false IsArray:false IsOptional:false}

	fieldIntent, err := p.Intent.Serialize()
	if err != nil {
		return nil, err
	}
	dataBuffer = append(dataBuffer, fieldIntent...)

	serializedLength, err := VarInt(len(packetIdBytes) + len(dataBuffer)).Serialize()
	if err != nil {
		return nil, err
	}

	buffer = append(buffer, serializedLength...)
	buffer = append(buffer, packetIdBytes...)

	buffer = append(buffer, dataBuffer...)

	return buffer, nil
}
