// Code generated by gen --type=LoginFinished --id=0x02; DO NOT EDIT.

package packets

import (
	"io"
)

func DeserializeLoginFinished(reader io.Reader) (LoginFinished, int, error) {

	fieldUUID, _, err := DeserializeUUID(reader)
	if err != nil {
		return LoginFinished{}, 0, err
	}

	fieldName, _, err := DeserializeString(reader)
	if err != nil {
		return LoginFinished{}, 0, err
	}

	fieldProperties, _, err := DeserializeVarInt(reader)
	if err != nil {
		return LoginFinished{}, 0, err
	}

	fieldStrict, _, err := DeserializeBoolean(reader)
	if err != nil {
		return LoginFinished{}, 0, err
	}

	return LoginFinished{
		UUID: fieldUUID,

		Name: fieldName,

		Properties: fieldProperties,

		Strict: fieldStrict,
	}, 0, nil
}

func (p LoginFinished) Serialize() ([]byte, error) {
	buffer := make([]byte, 0)

	packetIdBytes, err := VarInt(2).Serialize()
	if err != nil {
		return nil, err
	}

	dataBuffer := make([]byte, 0)

	fieldUUID, err := p.UUID.Serialize()
	if err != nil {
		return nil, err
	}
	dataBuffer = append(dataBuffer, fieldUUID...)

	fieldName, err := p.Name.Serialize()
	if err != nil {
		return nil, err
	}
	dataBuffer = append(dataBuffer, fieldName...)

	fieldProperties, err := p.Properties.Serialize()
	if err != nil {
		return nil, err
	}
	dataBuffer = append(dataBuffer, fieldProperties...)

	fieldStrict, err := p.Strict.Serialize()
	if err != nil {
		return nil, err
	}
	dataBuffer = append(dataBuffer, fieldStrict...)

	serializedLength, err := VarInt(len(packetIdBytes) + len(dataBuffer)).Serialize()
	if err != nil {
		return nil, err
	}

	buffer = append(buffer, serializedLength...)
	buffer = append(buffer, packetIdBytes...)
	buffer = append(buffer, dataBuffer...)

	return buffer, nil
}
