// Code generated by gen --type=LoginFinished --id=0x02; DO NOT EDIT.

package packets

import (
	"io"
)

func DeserializeLoginFinished(reader io.Reader) (LoginFinished, int, error) {

	fieldProfile, _, err := DeserializeGameProfile(reader)
	if err != nil {
		return LoginFinished{}, 0, err
	}

	fieldSessionId, _, err := DeserializeUUID(reader)
	if err != nil {
		return LoginFinished{}, 0, err
	}

	return LoginFinished{
		Profile: fieldProfile,

		SessionId: fieldSessionId,
	}, 0, nil
}

func (p LoginFinished) Serialize() ([]byte, error) {
	buffer := make([]byte, 0)

	packetIdBytes, err := VarInt(2).Serialize()
	if err != nil {
		return nil, err
	}

	dataBuffer := make([]byte, 0)

	fieldProfile, err := p.Profile.Serialize()
	if err != nil {
		return nil, err
	}
	dataBuffer = append(dataBuffer, fieldProfile...)

	fieldSessionId, err := p.SessionId.Serialize()
	if err != nil {
		return nil, err
	}
	dataBuffer = append(dataBuffer, fieldSessionId...)

	serializedLength, err := VarInt(len(packetIdBytes) + len(dataBuffer)).Serialize()
	if err != nil {
		return nil, err
	}

	buffer = append(buffer, serializedLength...)
	buffer = append(buffer, packetIdBytes...)

	buffer = append(buffer, dataBuffer...)

	return buffer, nil
}
