// Code generated by gen --type=LoginStart --id=0x00; DO NOT EDIT.

package packets

import (
	"io"
)

func DeserializeLoginStart(reader io.Reader) (LoginStart, int, error) {

	// {Name:Name Type:String IsJson:false IsPrefixed:false IsArray:false IsOptional:false}

	fieldName, _, err := DeserializeString(reader)
	if err != nil {
		return LoginStart{}, 0, err
	}

	// {Name:UUID Type:UUID IsJson:false IsPrefixed:false IsArray:false IsOptional:false}

	fieldUUID, _, err := DeserializeUUID(reader)
	if err != nil {
		return LoginStart{}, 0, err
	}

	return LoginStart{
		Name: fieldName,

		UUID: fieldUUID,
	}, 0, nil
}

func (p LoginStart) Serialize() ([]byte, error) {
	buffer := make([]byte, 0)

	packetIdBytes, err := VarInt(0).Serialize()
	if err != nil {
		return nil, err
	}

	dataBuffer := make([]byte, 0)

	// {Name:Name Type:String IsJson:false IsPrefixed:false IsArray:false IsOptional:false}

	fieldName, err := p.Name.Serialize()
	if err != nil {
		return nil, err
	}
	dataBuffer = append(dataBuffer, fieldName...)

	// {Name:UUID Type:UUID IsJson:false IsPrefixed:false IsArray:false IsOptional:false}

	fieldUUID, err := p.UUID.Serialize()
	if err != nil {
		return nil, err
	}
	dataBuffer = append(dataBuffer, fieldUUID...)

	serializedLength, err := VarInt(len(packetIdBytes) + len(dataBuffer)).Serialize()
	if err != nil {
		return nil, err
	}

	buffer = append(buffer, serializedLength...)
	buffer = append(buffer, packetIdBytes...)

	buffer = append(buffer, dataBuffer...)

	return buffer, nil
}
