// Code generated by gen --type=LoginAcknowledged --id=0x03; DO NOT EDIT.

package packets

import (
	"io"
)

func DeserializeLoginAcknowledged(reader io.Reader) (LoginAcknowledged, int, error) {

	return LoginAcknowledged{}, 0, nil
}

func (p LoginAcknowledged) Serialize() ([]byte, error) {
	buffer := make([]byte, 0)

	packetIdBytes, err := VarInt(3).Serialize()
	if err != nil {
		return nil, err
	}

	dataBuffer := make([]byte, 0)

	serializedLength, err := VarInt(len(packetIdBytes) + len(dataBuffer)).Serialize()
	if err != nil {
		return nil, err
	}

	buffer = append(buffer, serializedLength...)
	buffer = append(buffer, packetIdBytes...)
	buffer = append(buffer, dataBuffer...)

	return buffer, nil
}
