// Code generated by gen --type=PongResponse --id=0x01; DO NOT EDIT.

package packets

import (
	"io"
)

func DeserializePongResponse(reader io.Reader) (PongResponse, int, error) {

	fieldTimestamp, _, err := DeserializeLong(reader)
	if err != nil {
		return PongResponse{}, 0, err
	}

	return PongResponse{
		Timestamp: fieldTimestamp,
	}, 0, nil
}

func (p PongResponse) Serialize() ([]byte, error) {
	buffer := make([]byte, 0)

	packetIdBytes, err := VarInt(1).Serialize()
	if err != nil {
		return nil, err
	}

	dataBuffer := make([]byte, 0)

	fieldTimestamp, err := p.Timestamp.Serialize()
	if err != nil {
		return nil, err
	}
	dataBuffer = append(dataBuffer, fieldTimestamp...)

	serializedLength, err := VarInt(len(packetIdBytes) + len(dataBuffer)).Serialize()
	if err != nil {
		return nil, err
	}

	buffer = append(buffer, serializedLength...)
	buffer = append(buffer, packetIdBytes...)
	buffer = append(buffer, dataBuffer...)

	return buffer, nil
}
