// Code generated by gen --type=StatusRequest --id=0x00; DO NOT EDIT.

package packets

import (
	"io"
)

func DeserializeStatusRequest(reader io.Reader) (StatusRequest, int, error) {

	return StatusRequest{}, 0, nil
}

func (p StatusRequest) Serialize() ([]byte, error) {
	buffer := make([]byte, 0)

	packetIdBytes, err := VarInt(0).Serialize()
	if err != nil {
		return nil, err
	}

	dataBuffer := make([]byte, 0)

	serializedLength, err := VarInt(len(packetIdBytes) + len(dataBuffer)).Serialize()
	if err != nil {
		return nil, err
	}

	buffer = append(buffer, serializedLength...)
	buffer = append(buffer, packetIdBytes...)
	buffer = append(buffer, dataBuffer...)

	return buffer, nil
}
