// Code generated by gen --type=StatusResponse --id=0x00; DO NOT EDIT.

package packets

import (
	"encoding/json"
	"io"
)

func DeserializeStatusResponse(reader io.Reader) (StatusResponse, int, error) {
	return StatusResponse{}, 0, nil
}

func (p StatusResponse) Serialize() ([]byte, error) {
	buffer := make([]byte, 0)

	packetIdBytes, err := VarInt(0).Serialize()
	if err != nil {
		return nil, err
	}

	dataBuffer := make([]byte, 0)

	fieldResponse, err := json.Marshal(p.Response)
	if err != nil {
		return nil, err
	}

	fieldResponseLength, err := VarInt(len(fieldResponse)).Serialize()
	if err != nil {
		return nil, err
	}

	dataBuffer = append(dataBuffer, fieldResponseLength...)
	dataBuffer = append(dataBuffer, fieldResponse...)

	serializedLength, err := VarInt(len(packetIdBytes) + len(dataBuffer)).Serialize()
	if err != nil {
		return nil, err
	}

	buffer = append(buffer, serializedLength...)
	buffer = append(buffer, packetIdBytes...)
	buffer = append(buffer, dataBuffer...)

	return buffer, nil
}
